version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-webpub-pipeline
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    command: sleep infinity 
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/youtube_db

  mongodb:
    image: mongo:latest
    container_name: youtube-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    # environment:
      # optional but recommended if you want auth
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongo-data: {}
